{% set pkgname = "python-confluent-kafka" %}
{% set name = "confluent-kafka" %}
{% set version = "2.2.0" %}

package:
  name: {{ pkgname|lower }}
  version: {{ version }}

source:
  url: https://github.com/confluentinc/confluent-kafka-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ee099702bd5fccd3ce4916658fed4c7ef28cb22e111defb843d27633100ff065
  patches:
    - 0001-Fix-setup-for-windows.patch  # [win]

build:
  number: 0
  skip: True # [py<38 or s390x]
  script:
    - export CFLAGS="${CFLAGS} -I${PREFIX}/include"  # [unix]
    - export LDFLAGS="${LDFLAGS} -I${PREFIX}/lib"    # [unix]
    - set CFLAGS="%CFLAGS% /I%LIBRARY_INC%"          # [win]
    - set LDFLAGS="%LDFLAGS% /I%LIBRARY_LIB%"        # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - patch       # [osx and x86_64]
    - m2-patch    # [win64]
  host:
    - python
    - setuptools
    - pip
    - wheel
    - librdkafka
  run:
    - python
    - librdkafka

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - flake8
  imports:
    - confluent_kafka
  commands:
    - pip check
    - pytest tests/test_*.py

about:
  home: https://github.com/confluentinc/confluent-kafka-python
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: Apache
  summary: Confluent's Apache Kafka client for Python
  description: |
    Confluent's Kafka client for Python wraps the librdkafka C library,
    providing full Kafka protocol support with great performance and
    reliability.
  doc_url: http://docs.confluent.io/current/clients/confluent-kafka-python/index.html
  dev_url: https://github.com/confluentinc/confluent-kafka-python

extra:
  recipe-maintainers:
    - rmax
    - mrocklin
    - mariusvniekerk
    - duncanmmacleod
